version: '3.8'

services:
    app:
        container_name: locker-dev-app
        build:
            context: .
            dockerfile: ./.docker/angular/Dockerfile
            target: dev
            args:
                NODE_VER: 12
        volumes:
            - .:/app
        ports:
            - 4200:80
        command: sh -c '
            npm i
            &&
            ng serve --host 0.0.0.0 --port 80 --disable-host-check
            '
